<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>ASP.NET Core endpoint integration for OperationGuard.</Description>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../OperationGuard.Core/OperationGuard.Core.csproj" />
  </ItemGroup>
</Project>
