<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/OperationGuard.AspNetCore/OperationGuard.AspNetCore.csproj" />
    <ProjectReference Include="../../src/OperationGuard.PostgreSql/OperationGuard.PostgreSql.csproj" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
